services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "${HOST_POSTGRES_PORT:-65432}:5432"
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "${HOST_MAIL_SMTP_PORT:-11025}:1025"
      - "${HOST_MAIL_HTTP_PORT:-11080}:1080"
