version: "2.4"
services:
  postgres_dev:
    container_name: "clone-tabnews-database-1"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5432:5432"
